openapi: '3.0.3'

info:
  title: post-service
  version: 0.0.1

paths:
  /posts:
    get:
      operationId: GetPosts
      tags:
        - collection
      description: Retrieve a collection of posts
      responses:
        200:
          description: A list of post objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: CreatePost
      tags:
        - collection
      description: Create a post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        201:
          description: The newly created post including assigned ID and timestamp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'

  /posts/{id}:
    get:
      operationId: GetPost
      tags:
      - individual
      description: Retrieve a post
      parameters:
        - $ref: '#/components/parameters/PathID'
      responses:
        200:
          description: A post object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        404:
          $ref: '#/components/responses/404'
    patch:
      operationId: UpdatePost
      tags:
        - individual
      description: Update a post
      parameters:
        - $ref: '#/components/parameters/PathID'
      responses:
        200:
          description: An updated post object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
    delete:
      operationId: DeletePost
      tags:
        - individual
      description: Delete a post
      parameters:
        - $ref: '#/components/parameters/PathID'
      responses:
        204:
          description: Successfully deleted a post
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'

components:
  schemas:
    Post:
      description: Schema representing a single post
      type: object
      properties:
        id:
          type: string
          description: An ID uniquely identifying a post
          example: cb21cff0-bd76-46c7-98b7-f9fa545714e8
          readOnly: true
        title:
          type: string
          description: The title of the post
          example: Finally arrived!
        time:
          type: string
          description: The date and time the post was submitted in ISO 8601 format
          example: 2019-09-26T07:58:30.996+0200
          readOnly: true
        content:
          type: string
          description: The content of the post
          example: What an amazing trip! Some days have been long. Some have been way too short.

  responses:
    401:
      description: Invalid authentication
    403:
      description: Invalid authorization
    404:
      description: Not found

  parameters:
    PathID:
      in: path
      name: id
      description: The ID of the post to retrieve
      required: true
      schema:
        type: string
        example: cb21cff0-bd76-46c7-98b7-f9fa545714e8
