/*
 * post-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeletePost - 
func DeletePost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPost - 
func GetPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdatePost - 
func UpdatePost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
