/*
 * post-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreatePost - 
func CreatePost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPosts - 
func GetPosts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
