name: CD

on:
  push:
    branches: [ main ]
    paths:
      - pkg/**
      - main.go
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - run: make check

    - name: Github Tag Bump
      id: bump_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: main
        WITH_V: true

    - run: echo "image_registry=ghcr.io/tuuturu" >> $GITHUB_ENV
    - run: echo "image_name=motoblog-post-service" >> $GITHUB_ENV
    - run: echo "image_version=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV
    - run: echo "image_uri=${{ env.image_registry }}/${{ env.image_name}}:${{ env.image_version}}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build --tag ${{ env.image_uri }} .

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.image_uri }}
